# Generated by Django 4.0.4 on 2022-07-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0006_alter_measurement_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
