# Generated by Django 4.0.4 on 2022-07-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0008_alter_sensor_description_alter_sensor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
